spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: inventory-service
          uri: lb:http://inventory-service
          predicates:
            - Path=/api/inventory/**

        - id: order-service
          uri: lb:http://order-service
          predicates:
            - Path=/api/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


