spring:
  application:
    name: inventory-service2

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

