spring:
  application:
    name: inventory-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
